local cp = require("catppuccin.api.colors").get_colors() -- fetch colors with API
cp.crust = "#000000"
return {
  TSFuncBuiltin = { fg = cp.lavender, bold = true },
  TSConditional = { italic = true, fg = cp.mauve },
  TSKeywordOperator = { bold = true, fg = cp.mauve },
  TSInclude = { bold = true, fg = cp.mauve },
  VertSplit = { fg = cp.overlay2, bg = "#000000" },
  rainbowcol1 = { fg = cp.pink },
  rainbowcol2 = { fg = cp.mauve },
  rainbowcol3 = { fg = cp.rosewater },
  rainbowcol4 = { fg = cp.maroon },
  rainbowcol5 = { fg = cp.red },
  rainbowcol6 = { fg = cp.blue },
  rainbowcol7 = { fg = cp.peach },
  rainbowcol8 = { fg = cp.flamingo },
  BufferLineFill = { bg = "#000000" },
  BufferLineBufferSelected = { bg = cp.crust },
  BufferLineDuplicateSelected = { bg = cp.crust },
  BufferLineIndicatorSelected = { fg = cp.maroon, bg = cp.crust },
  BufferLineSeparator = { bg = "#000000", fg = "#000000" },
  BufferLineModified = { bg = cp.crust },
  BufferLineModifiedSelected = { bg = cp.crust },
  NormalFloat = { bg = cp.crust },
  FloatBorder = { bg = "#000000", fg = cp.blue },
  Float = { bg = cp.crust },
  WhichKeyFloat = { bg = "#000000" },
  NeoTreeNormal = { bg = "#000000" },
  DiagnosticError = { fg = cp.red },
  DiagnosticWarn = { fg = cp.yellow },
  DiagnosticInfo = { fg = cp.blue },
  DiagnosticHint = { fg = cp.rosewater },
  -- TelescopeNormal = { fg = cp.text, bg = cp.crust },
  -- TelescopeSelection = { bg = cp.base },
  -- TelescopeTitle = { fg = cp.text },
  -- TelescopeMatching = { fg = cp.peach },
  -- TelescopePromptTitle = { fg = cp.crust, bg = cp.rosewater },
  -- TelescopePromptNormal = { fg = cp.text, bg = cp.crust },
  -- TelescopePromptPrefix = { fg = cp.yellow, bg = cp.crust },
  -- TelescopePromptCounter = { fg = cp.yellow },
  -- TelescopeResultsTitle = { fg = cp.crust, bg = cp.crust },
  -- TelescopeResultsNormal = { fg = cp.text, bg = cp.crust },
  -- TelescopePreviewTitle = { fg = cp.crust, bg = cp.maroon },
  -- TelescopePreviewNormal = { fg = cp.text, bg = cp.crust },
  -- TelescopeBorder = { fg = cp.crust, bg = cp.crust },
  -- TelescopeResultsBorder = { fg = cp.crust, bg = cp.crust },
  -- TelescopePromptBorder = { fg = cp.crust, bg = cp.crust },
  -- TelescopePreviewBorder = { fg = cp.crust, bg = cp.crust },
}
