local cp = require("catppuccin.palettes").get_palette()
return {
  TSFuncBuiltin = { fg = cp.lavender, bold = true },
  rainbowcol2 = { fg = cp.lavender },
  TSConditional = { italic = true, fg = cp.mauve },
  TSKeywordOperator = { bold = true, fg = cp.mauve },
  TSInclude = { bold = true, fg = cp.mauve },
  VertSplit = { fg = cp.overlay0, bg = "#000000" },
  BufferLineFill = { bg = "#000000" },
  BufferLineBufferSelected = { bg = "#000000" },
  BufferLineDuplicateSelected = { bg = "#000000" },
  BufferLineIndicatorSelected = { fg = cp.maroon, bg = "#000000" },
  BufferLineSeparator = { bg = "#000000", fg = "#000000" },
  BufferLineModified = { bg = "#000000" },
  BufferLineModifiedSelected = { bg = "#000000" },
  NormalFloat = { bg = "#000000" },
  FloatBorder = { bg = "#000000", fg = cp.blue },
  Float = { bg = "#000000" },
  WhichKeyFloat = { bg = "#000000" },
  NeoTreeNormal = { bg = "#000000" },
  DiagnosticError = { fg = cp.red },
  DiagnosticWarn = { fg = cp.yellow },
  DiagnosticInfo = { fg = cp.blue },
  DiagnosticHint = { fg = cp.rosewater },
  TelescopeBorder = { fg = cp.blue },
}
