return {
  bufferline = true,
  neo_tree = true,
  lualine = true,
  gitsigns = true,
  colorizer = true,
  toggle_term = true,
  comment = true,
  symbols_outline = true,
  indent_blankline = true,
  dashboard = false,
  which_key = true,
  neoscroll = true,
  ts_rainbow = true,
  ts_autotag = true,
}
