return {
  n = {
    ["<A-k>"] = { "<cmd>m .-2<CR>", desc = "move line up" },
    ["<A-j>"] = { "<cmd>m .+1<CR>", desc = "move line down" },
    ["n"] = { "nzzzv" },
    ["N"] = { "Nzzzv" },
    ["J"] = { "mzJ`z" },
    ["<C-w>x"] = { ":WinShift swap<cr>" },
    ["f"] = { ":HopChar1CurrentLine<cr>", desc = "Hop 1 Char Current Line" },
    ["F"] = { ":HopChar1<cr>", desc = "Hop 1 Char Whole Buf" },
    ["<A-c>"] = { ":VCoolor<cr>", desc = "VCoolor" },
    ["<b"] = false,
    [">b"] = false,
    ["<leader>h"] = false,
    ["<leader>tp"] = false,
    ["<leader>tl"] = false,
    ["<leader>tu"] = false,
    ["<leader>tt"] = false,
    ["<leader>tn"] = false,
    ["<leader>c"] = false,
    ["<leader>fh"] = false,
    ["<leader>u"] = false,
    ["<leader>o"] = false,
  },
  v = {
    ["<A-j>"] = { ":m '>+1<cr>gv=gv" },
    ["<A-k>"] = { ":m '<-2<cr>gv=gv" },
  },
  i = {
    [","] = ",<c-g>u",
    ["."] = ".<c-g>u",
    ["!"] = "!<c-g>u",
    ["?"] = "?<c-g>u",
  },
}
