local C = require "user.dracula_theme.colors"

return {
  NotifyERRORBorder = { fg = C.red },
  NotifyWARNBorder = { fg = C.orange },
  NotifyINFOBorder = { fg = C.green },
  NotifyDEBUGBorder = { fg = C.cyan },
  NotifyTRACERBorder = { fg = C.purple },
  NotifyERRORIcon = { fg = C.red },
  NotifyWARNIcon = { fg = C.orange },
  NotifyINFOIcon = { fg = C.green },
  NotifyDEBUGIcon = { fg = C.cyan },
  NotifyTRACEIcon = { fg = C.purple },
  NotifyERRORTitle = { fg = C.red },
  NotifyWARNTitle = { fg = C.orange },
  NotifyINFOTitle = { fg = C.green },
  NotifyDEBUGTitle = { fg = C.cyan },
  NotifyTRACETitle = { fg = C.purple },
  NotifyERRORBody = { fg = C.fg },
  NotifyWARNBody = { fg = C.fg },
  NotifyINFOBody = { fg = C.fg },
  NotifyDEBUGBody = { fg = C.fg },
  NotifyTRACEBody = { fg = C.fg },
  NotifyLogTime = { fg = C.white },
  NotifyLogTitle = { fg = C.cyan },
}
