local C = require "user.dracula_theme.colors"
return {
  TSBoolean = { fg = C.bright_cyan, bold = true },
  TSConstant = { fg = C.orange, italic = true },
  TSVariable = { fg = C.bright_purple },
  TSFunction = { fg = C.green, bold = true },
  TSKeyword = { fg = C.pink, bold = true },
  TSInclude = { fg = C.pink, bold = true },
  TSConstructor = { fg = C.cyan, bold = true },
  TSKeywordOperator = { fg = C.pink, bold = true },
  TSKeywordFunction = { fg = C.cyan, bold = true, italic = true },
  TSConditional = { fg = C.pink, italic = true, bold = true },
  TSRepeat = { fg = C.pink, italic = true, bold = true },
  TSField = { fg = C.fg },
  TSVariableBuiltin = { fg = C.purple, italic = true },
  TSError = { fg = C.bright_red },
  TSPunctDelimiter = { fg = C.fg },
  TSPunctBracket = { fg = C.fg },
  TSPunctSpecial = { fg = C.fg },
  TSConstantBuiltin = { fg = C.purple },
  TSConstMacro = { fg = C.cyan },
  TSStringRegex = { fg = C.red },
  TSString = { fg = C.yellow },
  TSStringEscape = { fg = C.cyan },
  TSCharacter = { fg = C.green },
  TSNumber = { fg = C.purple },
  TSFloat = { fg = C.green },
  TSAnnotation = { fg = C.yellow },
  TSAttribute = { fg = C.cyan },
  TSNamespace = { fg = C.orange },
  TSFuncBuiltin = { fg = C.cyan },
  TSFuncMacro = { fg = C.green },
  TSParameter = { fg = C.orange },
  TSParameterReference = { fg = C.orange },
  TSMethod = { fg = C.green },
  TSProperty = { fg = C.fg },
  TSLabel = { fg = C.cyan },
  TSOperator = { fg = C.pink },
  TSException = { fg = C.purple },
  TSType = { fg = C.blue },
  TSTypeBuiltin = { fg = C.cyan },
  TSStructure = { fg = C.purple },
  TSText = { fg = C.orange },
  TSStrong = { fg = C.orange, bold = true }, -- bold
  TSEmphasis = { fg = C.yellow, italic = true }, -- italic
  TSUnderline = { fg = C.orange, underline = true },
  TSTitle = { fg = C.pink }, -- title
  TSLiteral = { fg = C.yellow }, -- inline code
  TSURI = { fg = C.yellow }, -- urls
  TSConstBuiltin = { fg = C.orange },
  TSStringEscap = { fg = C.yellow },
  TSTag = { fg = C.bright_yellow },
  TSTagDelimiter = { fg = C.fg },
  rainbowcol1 = { bold = true, fg = C.bright_magenta },
  rainbowcol2 = { bold = true, fg = C.green },
  rainbowcol3 = { bold = true, fg = C.bright_cyan },
  rainbowcol4 = { bold = true, fg = C.bright_purple },
  rainbowcol5 = { bold = true, fg = C.pink },
  rainbowcol6 = { bold = true, fg = C.bright_green },
  rainbowcol7 = { bold = true, fg = C.bright_magenta },
}
