local map = vim.keymap.set
local unmap = vim.keymap.del
-- Set key bindings
map("n", "<A-k>", "<cmd>m .-2<CR>")
map("n", "<A-j>", "<cmd>m .+1<CR>")
map("n", "n", "nzzzv")
map("n", "N", "Nzzzv")
map("n", "J", "mzJ`z")
map("i", ",", ",<c-g>u")
map("i", ".", ".<c-g>u")
map("i", "!", "!<c-g>u")
map("i", "?", "?<c-g>u")
map("v", "<A-j>", ":m '>+1<cr>gv=gv")
map("v", "<A-k>", ":m '<-2<cr>gv=gv")
map("n", "<C-w>x", ":WinShift swap<cr>")
map("n", "<C-s>", vim.diagnostic.open_float)
map("i", "<C-s>", vim.diagnostic.open_float)
map("n", "f", ":HopChar1CurrentLine<cr>")
map("n", "F", ":HopChar2<cr>")
-- Unmap
unmap("n", "<leader>fw")
unmap("n", "<leader>fo")
unmap("n", "<leader>ff")
unmap("n", "<leader>fh")
unmap("n", "<leader>fb")
unmap("n", "<leader>c")
unmap("n", "<leader>w")
